name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-15
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: prefix-dev/setup-pixi@v0.10.0
        with:
          pixi-version: v0.81.0
          locked: true
          cache: true

      - run: pixi run check
